Adds the zombie and leprechaun cards
vigetlabs/boom pull request #24
Opened 2021-03-05 23:16 UTC by clatwell

2021-03-05 23:16 UTC, clatwell commented on app/models/player.rb
> +        self.conditions = Array(card.bestows_condition).map { |c| c.new }
Got some help from David on this one

2021-03-06 02:56 UTC, efatsi commented on app/models/player.rb
> +        self.conditions = Array(card.bestows_condition).map { |c| c.new }
why? is there a card that bestows multiple conditions?

2021-03-06 02:56 UTC, efatsi approved these changes

2021-03-06 05:53 UTC, efatsi requested changes
Zombie card needs:
- to bestow a condition (which is the mechanism to get effects to happen when card sharing)

Zombie condition needs:
- after_action: which makes sure everyone involved in the share turns into a zombie

2021-03-06 15:25 UTC, efatsi commented on app/models/conditions/zombie.rb
> +      target_player.update(card: this_player_card)
@clatwell have you tested this both ways? I fear that if the `target_player` is the zombie, then the `from_player`s card will duplicate itself instead of the zombie one

2021-03-06 16:30 UTC, efatsi approved these changes
I'M SORRY! Yes, `this_player_card` is always the Zombie, because it's the zombie condition that this happens in. Phew this app is twisty.

2021-03-06 16:33 UTC, merged